Repository JaMR94/JaMR94.github.io, pull requests merged in 2023-03, with the labels that each got.

#28 AboutUs
  package-lock.json
  package.json
  src/components/LoginPage.jsx
  src/components/RegisterPage.jsx
  src/components/aboutimg.jsx
  src/components/aboutlifestory.jsx
  src/components/aboutourphilosophy.jsx
  src/components/aboutustitulo.jsx
  src/img/chucky.png
  src/img/exa2.jpg
  src/img/example.jpg
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/pages/aboutpage.js
  src/styles/globals.css
Labels: enhancement

#29 quite algunas cosas que use de prueba
  src/components/navbar.jsx
  src/pages/about.js
  src/pages/contact.js
  src/pages/products.js
Labels: extra stuffs

#36 Creación de Footer
  package-lock.json
  package.json
Labels: documentation, enhancement

#37 my css styles are back >:p
  src/styles/globals.css
Labels: enhancement

#34 detalle de producto
  src/components/componentsDetaillProducts/butomSelectProducts.jsx
  src/components/componentsDetaillProducts/descriptionProducts.jsx
  src/components/componentsDetaillProducts/ejemplo.jsx
  src/components/componentsDetaillProducts/headerProducts.jsx
  src/components/componentsDetaillProducts/imgProducts.jsx
  src/components/componentsDetaillProducts/selectDescriptionProducts.jsx
  src/img/Ejemplo.jpg
  src/pages/DetaillProducts.js
Labels: enhancement, User-story, extra stuffs

#38 FOOTER-MERGE
  public/imgs/ecomm.jpg
  src/components/footer.jsx
  src/components/monthly.jsx
  src/pages/_app.js
  src/pages/index.js
  src/styles/Home.module.css
  src/styles/footer.module.css
  src/styles/globals.css
  src/styles/monthly.module.css
Labels: documentation, extra stuffs

#43 combinación y actualización del Merge anterior junto con posible optimización en hojas de estilos
  src/components/Layout.jsx
  src/components/homeblog/cardsection.jsx
  src/components/homeblog/inicio.jsx
  src/components/homeblog/space.jsx
  src/components/monthly.jsx
  src/images/placer.jpg
  src/img/placer 2.jpg
  src/img/placer3.jpg
  src/pages/_app.js
  src/pages/index.js
  src/styles/Home.module.css
  src/styles/Test.css
  src/styles/globals.css
Labels: enhancement, extra stuffs

#48 Update cardsection.jsx
  src/components/homeblog/cardsection.jsx
  src/pages/_app.js
  src/styles/About.css
  src/styles/Login&Register.css
Labels: enhancement, extra stuffs

#47 agregando mi css
  src/components/componentsDetaillProducts/butomSelectProducts.jsx
  src/components/componentsDetaillProducts/descriptionProducts.jsx
  src/components/componentsDetaillProducts/headerProducts.jsx
  src/components/componentsDetaillProducts/imgProducts.jsx
  src/components/componentsDetaillProducts/selectDescriptionProducts.jsx
  src/pages/DetaillProducts.js
  src/styles/butomSelectProducts.module.css
Labels: enhancement, User-story, extra stuffs

#51 en header pon lo que pusiste en test y deja test como estaba antes
  src/components/homeblog/cardsection.jsx
  src/pages/_app.js
  src/styles/header.css
  src/styles/inicio.css
Labels: bug, extra stuffs

#50 Header/edgarperez7
  src/components/header.jsx
  src/components/navbar.jsx
  src/styles/Test.css
Labels: bug, enhancement, invalid

#55 pagina inicio con responsivo a full
  src/components/homeblog/cardsection.jsx
  src/components/homeblog/space.jsx
  src/pages/index.js
  src/styles/globals.css
  src/styles/inicio.css
Labels: extra stuffs

#56 header
  src/styles/header.css
Labels: enhancement

#62 parche de los productos y el componente carrito
  src/components/Carrito.jsx
  src/pages/DetaillProducts.js
  src/styles/globals.css
Labels: documentation, enhancement, extra stuffs

#64 carrito terminado
  src/components/Layouts/Layout.jsx
  src/components/navbar.jsx
Labels: documentation, enhancement, extra stuffs

#63 SearchBar
  package-lock.json
  package.json
  src/components/Layouts/Layout.jsx
  src/components/SearchBar.jsx
  src/styles/SearchBar.module.css
Labels: enhancement

#67 About us/karen g13
  src/components/aboutimg.jsx
  src/components/aboutlifestory.jsx
  src/components/aboutourphilosophy.jsx
  src/components/aboutustitulo.jsx
  src/images/exa2.jpg
  src/images/example.jpg
  src/img/chucky.png
  src/styles/About.css
  src/styles/globals.css
Labels: bug, extra stuffs

#68 se organizo la barra de busqueda
  src/components/Layouts/Layout.jsx
  src/components/navbar.jsx
  src/styles/SearchBar.module.css
Labels: enhancement, extra stuffs

#69 Se modifico header
  src/components/navbar.jsx
  src/styles/header.css
Labels: enhancement

#71 Correccion de About Us
  src/components/aboutlifestory.jsx
  src/components/aboutourphilosophy.jsx
  src/components/aboutustitulo.jsx
  src/styles/About.css
Labels: extra stuffs

#72 Ajuste del Responsive
  src/components/footer.jsx
  src/styles/footer.module.css
  src/styles/globals.css
  src/styles/monthly.module.css
Labels: bug, documentation, enhancement, extra stuffs

#73 Header mejora
  src/components/navbar.jsx
  src/styles/header.css
Labels: enhancement

#77 maquetado final??
  package-lock.json
  package.json
  src/components/Checkout/pagos_form.jsx
  src/components/Contact_us/contact_form.jsx
  src/components/Contact_us/main_contacts.jsx
  src/components/Contact_us/telefonos.jsx
  src/components/Products/Products_title.jsx
  src/components/Products/cardsection.jsx
  src/components/Products/menunav.jsx
  src/pages/Contact_us.js
  src/pages/Productos.js
  src/pages/_app.js
  src/pages/index.js
  src/styles/ContactUs.css
  src/styles/Productos.css
  src/styles/inicio.css
  src/styles/pagos.css
Labels: enhancement

#76 header correcon
  src/components/navbar.jsx
  src/styles/header.css
Labels: enhancement

#78 Creacion de nav
  src/components/Navpage.jsx
  src/pages/Navpage.js
  src/styles/About.css
Labels: enhancement

#79 LINKS!!!!!
  src/components/Layouts/Layout.jsx
  src/components/Navpage.jsx
  src/components/homeblog/inicio.jsx
  src/components/navbar.jsx
  src/pages/_app.js
  src/styles/About.css
  src/styles/header.css
  src/styles/inicio.css
Labels: extra stuffs

#75 pequeno cambio para q se vea mejor los botones
  src/styles/butomSelectProducts.module.css
Labels: extra stuffs

#82 awd
  src/components/Checkout/pagos_form.jsx
  src/components/Contact_us/contact_form.jsx
  src/components/Navpage.jsx
  src/components/Products/cardsection.jsx
  src/components/homeblog/destacado.jsx
  src/components/homeblog/inicio.jsx
  src/pages/index.js
  src/styles/About.css
  src/styles/Productos.css
  src/styles/inicio.css
Labels: enhancement, extra stuffs

#83 SearchBar
  src/components/Layouts/Layout.jsx
  src/components/Navpage.jsx
  src/components/SearchBar.jsx
  src/styles/SearchBar.module.css
Labels: bug

#84 Cambios de secc monthly
  src/styles/globals.css
  src/styles/monthly.module.css
Labels: extra stuffs

#85 Cambios CSS Y Layout
  package-lock.json
  package.json
  src/components/Layouts/Layout2.jsx
  src/components/LoginPage.jsx
  src/components/RegisterPage.jsx
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/styles/Login&Register.css
Labels: extra stuffs

#86 el redireccionamiento a los diferentes detalles de los productos
  src/components/Products/cardsection.jsx
  src/components/componentsDetaillProducts/butomSelectProducts.jsx
  src/components/componentsDetaillProducts/descriptionProducts.jsx
  src/pages/DetaillProducts/[id].js
Labels: enhancement, good first issue

#87 acomodo de componentes a carpetas
  src/components/about_us/aboutimg.jsx
  src/components/about_us/aboutlifestory.jsx
  src/components/about_us/aboutourphilosophy.jsx
  src/components/about_us/aboutustitulo.jsx
  src/components/login_register/LoginPage.jsx
  src/components/login_register/RegisterPage.jsx
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/pages/aboutpage.js
Labels: extra stuffs

#100 cambios del profesor @abraham1669
  src/components/Products/cardsection.jsx
  src/pages/DetaillProducts/[id].js
  src/pages/Productos.js
Labels: extra stuffs

#99 Finalizacion de Navbar
  src/components/Navpage.jsx
  src/styles/About.css
Labels: extra stuffs

#101 contact us
  src/components/Contact_us/contact_form.jsx
Labels: enhancement

#103 Update pagos_form
  src/components/Checkout/pagos_form.jsx
  src/pages/formulario.js
  src/pages/transporter.js
Labels: extra stuffs

#115 arreglado los conflictos
  src/components/Checkout/pagos_form.jsx
  src/pages/formulario.js
  src/pages/transporter.js
Labels: enhancement, extra stuffs

#114 solución al error runtime error
  src/pages/DetaillProducts.js
  src/pages/DetaillProducts/[id].js
  src/pages/Productos.js
  src/pages/index.js
Labels: enhancement, extra stuffs

#109 Responsive About Us
  src/styles/About.css
Labels: extra stuffs

#104 SearchBar
  src/components/Navpage.jsx
  src/components/SearchBar.jsx
  src/components/homeblog/inicio.jsx
  src/styles/SearchBar.module.css
Labels: question, extra stuffs

#112 Actualización del texto_aboutustitulo
  src/components/about_us/aboutustitulo.jsx
Labels: enhancement

#111 Actualización del texto_Aboutourphilosophy
  src/components/about_us/aboutourphilosophy.jsx
Labels: enhancement

#116 Update menunav.jsx
  src/components/Products/menunav.jsx
Labels: enhancement, extra stuffs

#118 Carrito modificaciones estrella
  package-lock.json
  package.json
  src/components/Carrito.jsx
  src/styles/Carrito.module.css
Labels: bug, extra stuffs

#107 Finalización Responsive (FOOTER)
  src/components/Checkout/pagostitle.jsx
  src/components/Contact_us/contact_form.jsx
  src/components/Contact_us/titulo_contact.jsx
  src/components/componentsDetaillProducts/descriptionProducts.jsx
  src/components/componentsDetaillProducts/selectDescriptionProducts.jsx
  src/components/footer.jsx
  src/components/homeblog/inicio.jsx
  src/img/logo.jpg
  src/img/logo.png
  src/styles/footer.module.css
  src/styles/globals.css
  src/styles/monthly.module.css
Labels: documentation, enhancement, extra stuffs

#117 Extras & Hotfix
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-256x256.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/components/Layouts/Layout.jsx
  src/components/homeblog/features.jsx
  src/components/homeblog/space.jsx
  src/img/placer3.jpg
  src/styles/Productos.css
  src/styles/inicio.css
Labels: extra stuffs
